# Generated by Django 3.2.5 on 2021-07-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_availability', models.CharField(max_length=1000)),
                ('scooter_availability', models.CharField(max_length=1000)),
                ('truck_availability', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_capacity', models.IntegerField()),
                ('scooter_capacity', models.IntegerField()),
                ('truck_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_trucks', models.IntegerField()),
                ('number_of_bikes', models.IntegerField()),
                ('number_of_scooties', models.IntegerField()),
            ],
        ),
    ]
