# Generated by Django 3.2.5 on 2021-07-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='bike_availability',
            new_name='vehicle_availability',
        ),
        migrations.RenameField(
            model_name='capacity',
            old_name='bike_capacity',
            new_name='vehicle_capacity',
        ),
        migrations.RenameField(
            model_name='capacity',
            old_name='scooter_capacity',
            new_name='vehicle_id',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='scooter_availability',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='truck_availability',
        ),
        migrations.RemoveField(
            model_name='capacity',
            name='truck_capacity',
        ),
        migrations.AddField(
            model_name='availability',
            name='slot_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
