# Generated by Django 3.2.5 on 2021-07-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_alter_type_vehicle_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='VehicleType',
        ),
    ]
