# Generated by Django 3.2.5 on 2021-07-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_rename_type_vehicletype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='id',
        ),
        migrations.RemoveField(
            model_name='capacity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='id',
        ),
        migrations.AlterField(
            model_name='availability',
            name='slot_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='vehicle_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
