# Generated by Django 3.2.5 on 2021-07-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20210715_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclesPerDay',
            fields=[
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_type', models.IntegerField()),
                ('vehicle_count_per_day', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
