# Generated by Django 3.2.5 on 2021-07-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20210715_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesperday',
            name='vehicle_type',
            field=models.CharField(max_length=900),
        ),
    ]
